// src/constants/adminConstants.js

// ========================================
// DASHBOARD CONSTANTS
// ========================================
export const ADMIN_DASHBOARD_STATS_REQUEST = 'ADMIN_DASHBOARD_STATS_REQUEST'
export const ADMIN_DASHBOARD_STATS_SUCCESS = 'ADMIN_DASHBOARD_STATS_SUCCESS'
export const ADMIN_DASHBOARD_STATS_FAIL = 'ADMIN_DASHBOARD_STATS_FAIL'

export const ADMIN_REVENUE_REPORT_REQUEST = 'ADMIN_REVENUE_REPORT_REQUEST'
export const ADMIN_REVENUE_REPORT_SUCCESS = 'ADMIN_REVENUE_REPORT_SUCCESS'
export const ADMIN_REVENUE_REPORT_FAIL = 'ADMIN_REVENUE_REPORT_FAIL'

export const ADMIN_TOP_PRODUCTS_REQUEST = 'ADMIN_TOP_PRODUCTS_REQUEST'
export const ADMIN_TOP_PRODUCTS_SUCCESS = 'ADMIN_TOP_PRODUCTS_SUCCESS'
export const ADMIN_TOP_PRODUCTS_FAIL = 'ADMIN_TOP_PRODUCTS_FAIL'

// ========================================
// ORDERS CONSTANTS
// ========================================
export const ADMIN_ORDER_LIST_REQUEST = 'ADMIN_ORDER_LIST_REQUEST'
export const ADMIN_ORDER_LIST_SUCCESS = 'ADMIN_ORDER_LIST_SUCCESS'
export const ADMIN_ORDER_LIST_FAIL = 'ADMIN_ORDER_LIST_FAIL'

export const ADMIN_ORDER_DETAILS_REQUEST = 'ADMIN_ORDER_DETAILS_REQUEST'
export const ADMIN_ORDER_DETAILS_SUCCESS = 'ADMIN_ORDER_DETAILS_SUCCESS'
export const ADMIN_ORDER_DETAILS_FAIL = 'ADMIN_ORDER_DETAILS_FAIL'

export const ADMIN_ORDER_UPDATE_REQUEST = 'ADMIN_ORDER_UPDATE_REQUEST'
export const ADMIN_ORDER_UPDATE_SUCCESS = 'ADMIN_ORDER_UPDATE_SUCCESS'
export const ADMIN_ORDER_UPDATE_FAIL = 'ADMIN_ORDER_UPDATE_FAIL'
export const ADMIN_ORDER_UPDATE_RESET = 'ADMIN_ORDER_UPDATE_RESET'

export const ADMIN_ORDER_DELETE_REQUEST = 'ADMIN_ORDER_DELETE_REQUEST'
export const ADMIN_ORDER_DELETE_SUCCESS = 'ADMIN_ORDER_DELETE_SUCCESS'
export const ADMIN_ORDER_DELETE_FAIL = 'ADMIN_ORDER_DELETE_FAIL'

// ========================================
// CUSTOMERS CONSTANTS
// ========================================
export const ADMIN_CUSTOMER_LIST_REQUEST = 'ADMIN_CUSTOMER_LIST_REQUEST'
export const ADMIN_CUSTOMER_LIST_SUCCESS = 'ADMIN_CUSTOMER_LIST_SUCCESS'
export const ADMIN_CUSTOMER_LIST_FAIL = 'ADMIN_CUSTOMER_LIST_FAIL'

export const ADMIN_CUSTOMER_UPDATE_REQUEST = 'ADMIN_CUSTOMER_UPDATE_REQUEST'
export const ADMIN_CUSTOMER_UPDATE_SUCCESS = 'ADMIN_CUSTOMER_UPDATE_SUCCESS'
export const ADMIN_CUSTOMER_UPDATE_FAIL = 'ADMIN_CUSTOMER_UPDATE_FAIL'
export const ADMIN_CUSTOMER_UPDATE_RESET = 'ADMIN_CUSTOMER_UPDATE_RESET'

export const ADMIN_CUSTOMER_DELETE_REQUEST = 'ADMIN_CUSTOMER_DELETE_REQUEST'
export const ADMIN_CUSTOMER_DELETE_SUCCESS = 'ADMIN_CUSTOMER_DELETE_SUCCESS'
export const ADMIN_CUSTOMER_DELETE_FAIL = 'ADMIN_CUSTOMER_DELETE_FAIL'
 
// ========================================
// PRODUCTS CONSTANTS
// ========================================
export const ADMIN_PRODUCT_LIST_REQUEST = 'ADMIN_PRODUCT_LIST_REQUEST'
export const ADMIN_PRODUCT_LIST_SUCCESS = 'ADMIN_PRODUCT_LIST_SUCCESS'
export const ADMIN_PRODUCT_LIST_FAIL = 'ADMIN_PRODUCT_LIST_FAIL'

export const ADMIN_PRODUCT_CREATE_REQUEST = 'ADMIN_PRODUCT_CREATE_REQUEST'
export const ADMIN_PRODUCT_CREATE_SUCCESS = 'ADMIN_PRODUCT_CREATE_SUCCESS'
export const ADMIN_PRODUCT_CREATE_FAIL = 'ADMIN_PRODUCT_CREATE_FAIL'
export const ADMIN_PRODUCT_CREATE_RESET = 'ADMIN_PRODUCT_CREATE_RESET'

export const ADMIN_PRODUCT_UPDATE_REQUEST = 'ADMIN_PRODUCT_UPDATE_REQUEST'
export const ADMIN_PRODUCT_UPDATE_SUCCESS = 'ADMIN_PRODUCT_UPDATE_SUCCESS'
export const ADMIN_PRODUCT_UPDATE_FAIL = 'ADMIN_PRODUCT_UPDATE_FAIL'
export const ADMIN_PRODUCT_UPDATE_RESET = 'ADMIN_PRODUCT_UPDATE_RESET'

export const ADMIN_PRODUCT_DELETE_REQUEST = 'ADMIN_PRODUCT_DELETE_REQUEST'
export const ADMIN_PRODUCT_DELETE_SUCCESS = 'ADMIN_PRODUCT_DELETE_SUCCESS'
export const ADMIN_PRODUCT_DELETE_FAIL = 'ADMIN_PRODUCT_DELETE_FAIL'

// ========================================
// CATEGORIES CONSTANTS
// ========================================
export const ADMIN_CATEGORY_LIST_REQUEST = 'ADMIN_CATEGORY_LIST_REQUEST'
export const ADMIN_CATEGORY_LIST_SUCCESS = 'ADMIN_CATEGORY_LIST_SUCCESS'
export const ADMIN_CATEGORY_LIST_FAIL = 'ADMIN_CATEGORY_LIST_FAIL'

export const ADMIN_CATEGORY_CREATE_REQUEST = 'ADMIN_CATEGORY_CREATE_REQUEST'
export const ADMIN_CATEGORY_CREATE_SUCCESS = 'ADMIN_CATEGORY_CREATE_SUCCESS'
export const ADMIN_CATEGORY_CREATE_FAIL = 'ADMIN_CATEGORY_CREATE_FAIL'
export const ADMIN_CATEGORY_CREATE_RESET = 'ADMIN_CATEGORY_CREATE_RESET'

// ========================================
// SERVICE PACKAGES CONSTANTS
// ========================================
export const ADMIN_SERVICE_LIST_REQUEST = 'ADMIN_SERVICE_LIST_REQUEST'
export const ADMIN_SERVICE_LIST_SUCCESS = 'ADMIN_SERVICE_LIST_SUCCESS'
export const ADMIN_SERVICE_LIST_FAIL = 'ADMIN_SERVICE_LIST_FAIL'

export const ADMIN_SERVICE_CREATE_REQUEST = 'ADMIN_SERVICE_CREATE_REQUEST'
export const ADMIN_SERVICE_CREATE_SUCCESS = 'ADMIN_SERVICE_CREATE_SUCCESS'
export const ADMIN_SERVICE_CREATE_FAIL = 'ADMIN_SERVICE_CREATE_FAIL'
export const ADMIN_SERVICE_CREATE_RESET = 'ADMIN_SERVICE_CREATE_RESET'

export const ADMIN_SERVICE_UPDATE_REQUEST = 'ADMIN_SERVICE_UPDATE_REQUEST'
export const ADMIN_SERVICE_UPDATE_SUCCESS = 'ADMIN_SERVICE_UPDATE_SUCCESS'
export const ADMIN_SERVICE_UPDATE_FAIL = 'ADMIN_SERVICE_UPDATE_FAIL'
export const ADMIN_SERVICE_UPDATE_RESET = 'ADMIN_SERVICE_UPDATE_RESET'

export const ADMIN_SERVICE_DELETE_REQUEST = 'ADMIN_SERVICE_DELETE_REQUEST'
export const ADMIN_SERVICE_DELETE_SUCCESS = 'ADMIN_SERVICE_DELETE_SUCCESS'
export const ADMIN_SERVICE_DELETE_FAIL = 'ADMIN_SERVICE_DELETE_FAIL'

export const ADMIN_CATEGORY_UPDATE_REQUEST = 'ADMIN_CATEGORY_UPDATE_REQUEST'
export const ADMIN_CATEGORY_UPDATE_SUCCESS = 'ADMIN_CATEGORY_UPDATE_SUCCESS'
export const ADMIN_CATEGORY_UPDATE_FAIL = 'ADMIN_CATEGORY_UPDATE_FAIL'
export const ADMIN_CATEGORY_UPDATE_RESET = 'ADMIN_CATEGORY_UPDATE_RESET'

export const ADMIN_CATEGORY_DELETE_REQUEST = 'ADMIN_CATEGORY_DELETE_REQUEST'
export const ADMIN_CATEGORY_DELETE_SUCCESS = 'ADMIN_CATEGORY_DELETE_SUCCESS'
export const ADMIN_CATEGORY_DELETE_FAIL = 'ADMIN_CATEGORY_DELETE_FAIL'

export const ADMIN_CATEGORY_DELETE_RESET = 'ADMIN_CATEGORY_DELETE_RESET'
export const ADMIN_PRODUCT_DELETE_RESET = 'ADMIN_PRODUCT_DELETE_RESET'

export const ADMIN_SERVICE_DELETE_RESET = 'ADMIN_SERVICE_DELETE_RESET'