// src/constants/bookingConstants.js

// Service List
export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST'
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS'
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL'

// Service Details
export const SERVICE_DETAILS_REQUEST = 'SERVICE_DETAILS_REQUEST'
export const SERVICE_DETAILS_SUCCESS = 'SERVICE_DETAILS_SUCCESS'
export const SERVICE_DETAILS_FAIL = 'SERVICE_DETAILS_FAIL'

// Booking Create
export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET'

// Booking List (My Bookings)
export const BOOKING_LIST_MY_REQUEST = 'BOOKING_LIST_MY_REQUEST'
export const BOOKING_LIST_MY_SUCCESS = 'BOOKING_LIST_MY_SUCCESS'
export const BOOKING_LIST_MY_FAIL = 'BOOKING_LIST_MY_FAIL'

// Booking Details
export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

// Booking Cancel
export const BOOKING_CANCEL_REQUEST = 'BOOKING_CANCEL_REQUEST'
export const BOOKING_CANCEL_SUCCESS = 'BOOKING_CANCEL_SUCCESS'
export const BOOKING_CANCEL_FAIL = 'BOOKING_CANCEL_FAIL'
export const BOOKING_CANCEL_RESET = 'BOOKING_CANCEL_RESET'